### ISSUE TITLE
Shortcode Editor

### ISSUE THREAD

**Issue by rramo012** [BoldGrid/post-and-page-builder#100]
Add an editor that allows a user to customize shortcodes values. As of the 1.11.0 release, users will be able to see the visual representation of a shortcode within the editor. Once the user clicks the pencil edit icon, they should be allowed to edit the shortcode.

The editor could be a list of key value pair input boxes

**Comment by rramo012** [comment]
Testing

- Add a shortcode to a page. 
- Click on the pencil icon.
- edit the shortcode text
- click update
- The UI should update

**Comment by nicolepaschen** [comment]
I do not see a pencil above this shortcode.

![image](https://user-images.githubusercontent.com/20601160/68502787-44403b00-022f-11ea-9ba8-1734eded46d3.png)

**Comment by nicolepaschen** [comment]
I used Shortcodes Ultimate and saw the new feature, but the default popup size had a vertical scrollbar to get to the buttons.

![image](https://user-images.githubusercontent.com/20601160/68505113-7b651b00-0234-11ea-84ed-149f2feed63b.png)
