### ISSUE TITLE
Bug: Sorting problem with Post List widget

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/post-and-page-builder#104]
**Describe the bug**
Using the sorting feature of the Post List widget does not always display posts in the expected order (Newest or Oldest).  The widget appears to use the Last Updated timestamp rather than the date it was published for sorting purposes. This leads to a unexpected ordering for users since the date displayed on each post in the widget uses the publish date instead of when it was last updated.

**Expected behavior**
Posts should be ordered in the list based on their published date instead of when they were last updated.  

**Screenshots**
![image](https://user-images.githubusercontent.com/17650704/64636882-a23bd800-d3d0-11e9-98e9-4f9a041da658.png)

**Comment by rramo012** [comment]
The fix has been implemented in the premium ext. A new version will be released within the next week. Version 1.0.4
