### ISSUE TITLE
Feature: Add Search Element to the Add Icon modal

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/post-and-page-builder#105]
**Is your feature request related to a problem? Please describe.**
When adding an icon to a post or page, the icons are listed without an obvious sort order, and there are a large amount to choose from. This leads to a frustrating user experience scrolling to locate the icon needed for a specific purpose.

**Describe the solution you'd like**
A text input at the top of the modal, allowing the user to filter the listed icons according to a search term.

**Describe alternatives you've considered**
Alphabetizing the listed icons would also improve the user experience, but the scroll distance for the entire list is still extremely long.

**Additional context**
![Selection_163](https://user-images.githubusercontent.com/8019842/65162530-9ebed700-d9f6-11e9-92a1-b1860995a9cf.png)
This feature request is related to user feedback submitted through the BoldGrid Forums:
https://www.boldgrid.com/feedback/communities/8/topics/5088-adding-icons-is-a-pain

**Comment by jessecowens** [comment]
[Additonal user feedback has been received for this issue](https://www.boldgrid.com/support/page-builder/icons/#comment-2892) on the BoldGrid Support Center.

**Comment by jessecowens** [comment]
[Another user has requested this feature](https://www.boldgrid.com/support/page-builder/icons/#comment-3102) on the BoldGrid Support Center.

**Comment by jessecowens** [comment]
[Another user has requested this feature](https://www.boldgrid.com/support/page-builder/icons/#comment-3107) on the BoldGrid Support Center.

**Comment by jamesros161** [comment]
Look into adding categories / accordians

**Comment by nicolepaschen** [comment]
Please center the search box on the main popover.

**Comment by nicolepaschen** [comment]
should it stay sticky at the top as the user scrolls? The overall height of the box should stay the same tho, so show less icons if you do that please.
