### ISSUE TITLE
Horizontal Lines do not display correctly with Twenty Twenty

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#108]
Using WP5.3 RC3 and the theme Twenty Twenty the horizontal lines do not display correctly in the Editor. Front end display is correct. Single lines have a weird // in the middle. Double lines do not appear double. Decorative elements appear in the wrong place / skewed sideways.

**Screenshots**
![hr-display](https://user-images.githubusercontent.com/20601160/68218723-c8d25580-ffb2-11e9-9cd1-dee7f85525f7.PNG)

**Comment by rramo012** [comment]
https://github.com/BoldGrid/post-and-page-builder/commit/f63c5a1eaa13a09f30bafe374f568644f2a354c8

**Comment by nicolepaschen** [comment]
New lines appear correctly.

When I add a block with a line, it does not appear correctly.

**Comment by rramo012** [comment]
Thanks! I'll update the blocks. Those changes will be added on another repo.

**Comment by nicolepaschen** [comment]
added to https://github.com/BoldGrid/post-and-page-builder/issues/171
