### ISSUE TITLE
Twenty Twenty default page template isn't WYSIWYG

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#110]
Using WP5.3 RC3, activate Twenty Twenty theme and open the Customzier to see starter content. Publish. Do not install the PPB. The home page uses the Default Template.

Using the default WP editor, this is what I see:
![default-editor](https://user-images.githubusercontent.com/20601160/68223524-f1f6e400-ffba-11e9-826a-53626d25f8ff.PNG)

Install and use the PPB, use Theme Default template. This is what I see - the width is too small. Front end still displays correctly.
![default-ppb](https://user-images.githubusercontent.com/20601160/68223544-f9b68880-ffba-11e9-8bfb-2369d7a95401.PNG)

**Comment by nicolepaschen** [comment]
I started with the default template and then changed to cover and saved. When the page reloaded it was narrow. When I changed to default template it stayed narrow. Cover template is a full width design too.

**Comment by rramo012** [comment]
I'm going to put this on another ticket. The editor width resizing doesn't support detecting the new width of a page when changing to a non boldgrid template. I'll implement that through another ticket
