### ISSUE TITLE
Add Block Screen > Add Key display bug

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#114]
Add Block Screen > Add Key in upper left

The terms and conditions cheeckbox display looks strange

![add-block-key-box](https://user-images.githubusercontent.com/20601160/68503188-43f46f80-0230-11ea-8b9c-6ce37ef2d359.PNG)

**Comment by rramo012** [comment]
I am not able to replicate. Let me know what other plugins are active and which browser.

**Comment by nicolepaschen** [comment]
Cannot replicate now either
