### ISSUE TITLE
WP 5.5 - Cannot add blocks, DropTab and popovers missing

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#140]
Happens when using:
WP 5.5 Beta 3
PPB 1.13.1

Uncaught (in promise) ReferenceError: wpColorPickerL10n is not defined
    _create https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    jQuery 7
    _setupColorPicker https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    init https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    value https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    jQuery 7
    init https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    init https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    load_draggable https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    Editor https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/js/editor/editor.min.js?ver=1.13.1&wp-mce-49100-20200624:1
    fire https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2
    fire https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2
    yw https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2
    bw https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2
    loadAll https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2

**Comment by bwmarkle** [comment]
@rramo012 after some digging around, I have ended up here - https://github.com/kallookoo/wp-color-picker-alpha/issues/35

**Comment by nicolepaschen** [comment]
From James -  So it looks like these l10n issues are because WordPress removed a lot of the l10n localization from the core scripts, in favor of using i18n internationalization instead. Need to update Kirki
