### ISSUE TITLE
[Bug] Problems switching to WordPress editor in WP 5.5

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/post-and-page-builder#149]
**Describe the bug**
Attempting to switch to the WordPress editor while editing a Page or Post reverts back to PPB/Classic.

**To Reproduce**
1. Edit a page/post with the PPB interface
2. Switch to WordPress editor
3. The WP editor should show up for the first attempt
4. Change back to PPB and then try to go back to WP editor
5. The Visual editor will briefly show the WP editor and then revert to PPB automatically

**Screenshots**
![editor-switch](https://user-images.githubusercontent.com/17650704/90805569-cb0b6380-e2e9-11ea-8c2c-a52000500336.gif)

**Comment by rramo012** [comment]
Deployed - Version 1.13.4 - https://github.com/BoldGrid/post-and-page-builder/commit/564cade7912793d31cbefde3792c2dc668be688d

Cause: WP 5.5 now loads with the most recently loaded sidebar which cause the PPB "Sidebar" within gutenberg to activate as soon as the page loads.
