### ISSUE TITLE
PPB does not work with WordPress 5.6

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#155]
When testing with both the Beta 1 and Beta 2 versions of the upcoming WordPress 5.6 release (Dec 8) I found these issues:

Crio / Twenty Twenty - Cannot complete the initial setup, cannot add Blocks, DropTab is missing, fonts from Customizer do not pull thru as expected.

V1 Themes - Fonts from Customizer do not pull thru as expected. After going thru Inspirations, the **first** time I open a page I can add Blocks and I see the DropTab. When I go back into the page, or open other pages, that functionality breaks.

No console errors in FF.

**Comment by rramo012** [comment]
The first item here was fixed with https://github.com/BoldGrid/post-and-page-builder/commit/8226b369edd1760ad83078d6f6e62c39941f5cf9 .

Need some clarification on the second item: Does the editor fail to load or are we just having problems with fonts?

**Comment by nicolepaschen** [comment]
For me, the very first time I opened a page I could use PPB functionality but the fonts didn't pull thru from the v1 Customizer. Every other time I opened a page PPB functionality did not work.

**Comment by rramo012** [comment]
Closing this issue and creating a new issue regarding fonts not showing within ppb
