### ISSUE TITLE
WP 5.6 - Selected fonts from supported themes not displaying in editor

### ISSUE THREAD

**Issue by rramo012** [BoldGrid/post-and-page-builder#160]
From @nicolepaschen 

> V1 Themes - Fonts from Customizer do not pull thru as expected. After going thru Inspirations, the first time I open a page I can add Blocks and I see the DropTab. When I go back into the page, or open other pages, that functionality breaks.
> 
> For me, the very first time I opened a page I could use PPB functionality but the fonts didn't pull thru from the v1 Customizer. Every other time I opened a page PPB functionality did not work.

**Comment by nicolepaschen** [comment]
Crio fonts do not come thru from the Customizer either.
