### ISSUE TITLE
WP 5.6 - Missing Text Controls in editor from T in DropTab

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#161]
Using:
WP 5.6 RC 4 
PPB RC 1 

With Twenty Twenty, Twenty Twenty-One, v1 themes, and Crio, I am missing most of the Text Settings controls from the T in the DropTab.

![missing-text-settings-2020](https://user-images.githubusercontent.com/20601160/101374521-40407b80-387c-11eb-9abf-504d74bc0573.PNG)

**Comment by jamesros161** [comment]
I am able to replicate this issue when using Crio as well
