### ISSUE TITLE
WP 5.6 - Twenty Twenty-One theme background color from Customizer doesn't pull thru to editor

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#162]
Using:
WP 5.6 RC 4
PPB RC 1

With Twenty Twenty-One I changed the background color from the default green to a blue in the Customizer. When I edit the page, I see green still in the editor. 

New pages have green backgrounds as well.

![2021-colors](https://user-images.githubusercontent.com/20601160/101374760-944b6000-387c-11eb-8212-3ae1d2ebf5de.gif)

**Comment by jamesros161** [comment]
Also able to replicate this with 2021 theme. However, it appears the background color / pattern selections in Crio are pulling through as expected.
