### ISSUE TITLE
Editor does not show accurate fonts or background colors. 

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/post-and-page-builder#168]
**Describe the bug**
Post and Page Builder does not show the correct background colors or fonts in the editor. This issues seems to be mostly affecting Firefox. 

**To Reproduce**
1. Install PPB, Crio, and be sure to have WP5.6 installed.
2. Change the body background color to something other than the default white color. 
3. Set the font to something other than the default Exo 2
4. Go to the editor, and you will see that the fonts and background colors are not showing. 

*Note: Twenty Twenty one theme also doesn't seem to show the correct background colors of you have changed it from the default color. 

**Note: None of the Google Fonts seem to be loading. Try editing the font within the editor and see that the fonts don't update in the editor preview after changing it controls. 

**Screenshots**
The following console errors are shown as well. 
![image](https://user-images.githubusercontent.com/49331357/101556176-44f25600-3988-11eb-8b1f-4d77ed6ca80a.png)

**Comment by nicolepaschen** [comment]
![ff-crio-stable](https://user-images.githubusercontent.com/20601160/101556997-12495d00-398a-11eb-91a8-4089759715f9.gif)
