### ISSUE TITLE
Design elements of <hr> do not display correctly

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#171]
![image](https://user-images.githubusercontent.com/20601160/105519892-013d7c80-5ca8-11eb-9a74-da3b08064e7d.png)

Some of the Horizontal Line designs do not display as intended - the square is supposed to be on top of the line in this screenshot for example.

**Comment by jessecowens** [comment]
Additionally to this, there are some HR's included with starter content that are missing the necessary `bg-hr` class for the custom HR control to function:

https://user-images.githubusercontent.com/8019842/123845010-f0390d00-d8d0-11eb-84cc-5c3dc7f1a5bb.mp4

**Comment by nicolepaschen** [comment]
also happens in core themes- https://github.com/BoldGrid/post-and-page-builder/issues/108

**Comment by nicolepaschen** [comment]
no longer an issue, closing
