### ISSUE TITLE
[1.15.0 Alpha] Drag handles not working properly

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/post-and-page-builder#224]
[Harry] Section drag/handle and tool not showing - Cloud WP, even on reload (Could be PHP settings? Browser related?)

[JW] The Section drag handle appeared in the middle of the section for me in fullscreen mode. Controls showed up in the expected location when the page had a single block, but once I added more they started appearing in the wrong location.

https://docs.google.com/document/d/16ciz_xTBzlVam9q2OKLUQi9w94Pb0LNOjKcfOnp9qEE/edit#heading=h.ae402f2m9rw

**Comment by nicolepaschen** [comment]
Beta 2 - I cannot drag and drop columns when in tablet view. no console errors in Chrome.

![cannot-drag-tablet](https://user-images.githubusercontent.com/20601160/135505906-4b8af836-2a6a-4be2-aa3f-b1f6b03d80e5.gif)

**Comment by nicolepaschen** [comment]
I cannot drag all columns with Pavilion in tablet or mobile view. Some I can, some I can't unsure why the difference.

**Comment by nicolepaschen** [comment]
![pavilion](https://user-images.githubusercontent.com/20601160/140533967-1d21b560-d2e8-42a5-8e83-3c870f0dbde9.gif)

**Comment by nicolepaschen** [comment]
Cannot drag columns from the left side with the latest Crio build either - mobile view

**Comment by jamesros161** [comment]
As discussed, the column resize from the left side is behaving as expected. Users should not be able to drag from the far left on mobile or tablet views, because it breaks larger display layouts.
