### ISSUE TITLE
Initial Screen Container Size

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/post-and-page-builder#227]
{[NP] When I open full screen, I see a narrow content container. When I change the block to be full width, it kicks out. When I change the block to be contained again, the content container stays big but moves my cursor into the contained section as expected. Can it just be big all the time even if it’s a contained block? It’s weird that it jumps.

https://docs.google.com/document/d/16ciz_xTBzlVam9q2OKLUQi9w94Pb0LNOjKcfOnp9qEE/edit#heading=h.lasjn9f51fgp

**Comment by nicolepaschen** [comment]
Issue on RC1 with Twenty Twenty theme
