### ISSUE TITLE
[1.15.0 Alpha] Check size and alignment of the new buttons.

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/post-and-page-builder#229]
The Add Media and Add Block fonts don’t look aligned (could be optical illusion), and the space between them is not consistent with the rest of the toolbar

**Comment by nicolepaschen** [comment]
** The Add Media / Add block button have a space between them:
![gap](https://user-images.githubusercontent.com/20601160/135516473-e9bbf561-9918-441c-816b-5d666a579697.PNG)

The Save Draft / Preview buttons do not:
![no-gap](https://user-images.githubusercontent.com/20601160/135516464-14e2a805-c4a8-4d27-adaf-dd35403f9270.PNG)


** The Publish button is not the same blue as the Add Block button. 

** The hover effect on Save Draft and Preview are different. There is no hover effect on Publish. Recommend making them match the behavior on Add Media / Add Block buttons:
![hover-effects](https://user-images.githubusercontent.com/20601160/135517139-6bf311af-1745-49b2-8583-cc80fd6a8e68.gif)
