### ISSUE TITLE
[1.15.0 Beta] Images missing popover

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#250]
When I first added an image, it was missing the popover controls in the Beta. When I saved the page and it refreshed, I saw them as expected.

Stable:
![stable](https://user-images.githubusercontent.com/20601160/134704554-0306d2e2-0153-41a9-a627-dd440d32410c.jpg)

Beta:
![beta](https://user-images.githubusercontent.com/20601160/134704548-19ebc652-2bc9-4129-b502-797ecbb672bb.jpg)

**Comment by jamesros161** [comment]
I have gotten the image popover to work sometimes. I will continue troubleshooting this to have it resolved before the first RC release.

**Comment by nicolepaschen** [comment]
It is working for me in Chrome in Beta 2.
