### ISSUE TITLE
Button gets deleted when trying to replace the text

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#282]
When we removed the extra space before and after a link, we made it so you cannot replace text in a button easily:

![button](https://user-images.githubusercontent.com/20601160/140083929-73c4cac5-3c41-40fb-ae5b-1be26b00322f.gif)

**Comment by nicolepaschen** [comment]
There is now a space before and after the text when they do not in stable with 2021 theme:
![links](https://user-images.githubusercontent.com/20601160/165153212-c1446260-356f-4dea-a60a-81e97c522b5a.gif)

**Comment by nicolepaschen** [comment]
RC2 - non Crio themes are still difficult to work with

**Comment by jamesros161** [comment]
> 

I was unable to replicate this in Twenty Twenty One
