### ISSUE TITLE
[1.15.0 RC1] Add Connect Key box on Add Block screen needs styling adjusted

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#285]
I am using Twenty Twenty-One theme. When I go to the Add Block screen and click either the orange 'Add Connect Key' link in the upper left of the screen or 'Add Connect Key' when hovering on a block, the popup doesn't match stable styling.

RC:
![add-block-add-key](https://user-images.githubusercontent.com/20601160/140515352-c38b813f-2731-4a4f-84e4-d9a304f0fd13.PNG)

Stable:
![stable-add-block-add-key](https://user-images.githubusercontent.com/20601160/140515354-7ada50c6-7497-4ea0-a69b-cdbc1e6db98c.PNG)

**Comment by nicolepaschen** [comment]
weird, it looks fine now. Just double check please :)

**Comment by jamesros161** [comment]
Double checked on a clean install, and everything looks normal. Leaving this open for now, but moving it to under review, so we can look out for it again.
