### ISSUE TITLE
Hover Boxes

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#297]
I'd like to be able to set 2 backgrounds - one for normal and one for hover. Ideally this would be added to the column shape, column, and row controls.

**Comment by nicolepaschen** [comment]
I changed the hover effect to be a background color. When I published the page it reverted and didn't actually save my color.
![hover-box-color](https://user-images.githubusercontent.com/20601160/154113603-723d8e23-eaf6-4953-805d-a48cbb8cbf23.gif)

**Comment by nicolepaschen** [comment]
Please add a slight transition to the hover effect - it's pretty abrupt right now.

**Comment by nicolepaschen** [comment]
The heading for Hover Effects is at the bottom of the panel instead of the top: 

![image (1)](https://user-images.githubusercontent.com/20601160/154116226-36611ecb-0a26-42ea-b356-41849db340b7.png)

**Comment by nicolepaschen** [comment]
Background > Hover Effects > Background Image is missing BG Connect Search. The main Background Image panel has it.
![Screenshot_1](https://user-images.githubusercontent.com/20601160/154145578-6bcc15ae-335e-45ad-a433-fc670112ae05.jpg)

**Comment by nicolepaschen** [comment]
You can't hover on mobile or tablet and the average user isn't gonna think about that. Can we add a control to choose what content displays on touchscreen devices?

**Comment by nicolepaschen** [comment]
Ideally we want 2 complete sets of child element content to be created - one for standard and one for hover.

**Comment by jamesros161** [comment]
> Background > Hover Effects > Background Image is missing BG Connect Search. The main Background Image panel has it. ![Screenshot_1](https://user-images.githubusercontent.com/20601160/154145578-6bcc15ae-335e-45ad-a433-fc670112ae05.jpg)

This particular issue is with Inspirations. The new add media button has to be added to the list of selectors for connect-search.
However, if you open the 'add media' window for a standard background image, then close it, then open the 'add media' window for a hover image, it will show up.
