### ISSUE TITLE
console warning in PPB when loading submenus in Custom Page Headers.

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/post-and-page-builder#303]

**Comment by nicolepaschen** [comment]
I don't see the dropdowns consistently now. Sometimes I see it but when I save the page it goes away.

**Comment by nicolepaschen** [comment]
RC1 console errors from Joe 

PHP Warning:  Undefined variable $post_id in /home/nicolep/public_html/wp-content/themes/crio/inc/boldgrid-theme-framework/includes/class-boldgrid-framework-api.php on line 557

PHP Warning:  Trying to access array offset on value of type bool in /home/nicolep/public_html/wp-content/plugins/post-and-page-builder/includes/class-boldgrid-editor-theme.php on line 269

PHP Warning:  Attempt to read property "slug" on null in /home/nicolep/public_html/wp-content/plugins/post-and-page-builder/includes/class-boldgrid-editor-theme.php on line 269

Warning: Undefined array key "SERVER_NAME" in /home/nicolep/public_html/wp-content/plugins/post-and-page-builder/includes/config/config.plugin.php on line 18
