### ISSUE TITLE
[Bug] MCE is "squished" when additional controls are added

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/post-and-page-builder#305]
**Describe the bug**
If several 3rd-party plugins add buttons to TinyMCE, the editor display is squished down the left-hand side.

**To Reproduce**
1. Install [WordPress with several plugins](https://www.boldgrid.com/central/cloud-wordpress/try?plugins=post-and-page-builder,re-add-text-justify-button,wp-statistics,pdf-print,maxbuttons) that add controls, for example: re-add-text-justify-button, wp-statistics, pdf-print, max-buttons
2. Edit a page or post

**Screenshots**
![image](https://user-images.githubusercontent.com/8019842/143945754-80340bcb-4056-4380-af8c-de19214c2058.png)

**Comment by jamesros161** [comment]
As a note.... This seems to be caused by the mceu_xx ID numbers being changed when adding additional buttons
