### ISSUE TITLE
Add Menu Direction options.

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/post-and-page-builder#313]
Footer menus are usually vertical. The only way to have vertical menus right now is to use the standard WP Navigation Menu widget, as the one we made for Custom Page Headers only goes horizontal.

Can we add a toggle to the Navigation Menu widget we made for it to be vertical?
How else can I add a horizontal menu to a footer but still have font color / size / family controls?

**Comment by nicolepaschen** [comment]
RC1 - please update icon for vertical to be up and down

![vertical-icon-up-down](https://user-images.githubusercontent.com/20601160/145873838-36d3df95-06f8-42e8-bdef-a9e245f204ef.jpg)

**Comment by nicolepaschen** [comment]
RC1 - vertical menus do not line up - links after the first are indented
![vertical-menu-alignment](https://user-images.githubusercontent.com/20601160/145881113-99359d67-5f3a-48d5-a666-f22c55609694.PNG)

**Comment by nicolepaschen** [comment]
I didn't start with inspirations or starter content. I made a menu and the spacing between the items isn't even - the 2nd item is closer than it should be to the 1st. The hover effect helps show it:

![menu-2nd-item](https://user-images.githubusercontent.com/20601160/146477468-31ce6acb-d544-4377-9895-a28b8d4f2a34.gif)
