### ISSUE TITLE
[Bug] Fatal Error implode(): Argument #1 ($pieces) must be of type array

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/post-and-page-builder#322]
**Describe the bug**
In some cases, a fatal error is thrown while editing pages in a Version 1 BoldGrid Theme

**Comment by jamesros161** [comment]
It looks like this is caused by the new method `Boldgrid_Editor_Theme::get_background_classes()` returning a null value in some instances of V1 themes. 

I have linked a PR that should resolve this.
