### ISSUE TITLE
Allow filtering of Premium URL's in plugin

### ISSUE THREAD

**Issue by harryjackson1221** [BoldGrid/post-and-page-builder#397]
Resellers need the ability to override Premium URL's. As an example, here is the Pull Request adding this feature to Total Upkeep:
https://github.com/BoldGrid/boldgrid-backup/commit/6ce49a5c7fa6591df6f415ef15c145d39c1618a6

**Comment by bwmarkle** [comment]
@jamesros161 we need this for both P&PB and Crio
