### ISSUE TITLE
JavaScript Conflict with TinyMCE Advanced plugin

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/post-and-page-builder#439]
**Describe the bug**
If a user is using both the Post and Page Builder and the "[Advanced Editor Tools](https://wordpress.org/plugins/tinymce-advanced/)" plugin (formerly known as TinyMCE Advanced), JavaScript errors prevent using the PPB tools.
Advanced Editor Tools is one of the most popular plugins at >2 Million active installs.

**To Reproduce**
1. [Install WordPress with the PPB and Advanced Editor Tools](https://www.boldgrid.com/central/cloud-wordpress/try?plugins=post-and-page-builder,tinymce-advanced&theme=crio)
2. Edit a page or post
3. Note JavaScript errors and unresponsive "Add Block" button 

**Additional context**
This issue was reported in the [BoldGrid support forums](https://www.boldgrid.com/support/question/i-cant-add-a-block-in-the-latest-version-of-crio-wordpress-theme/)

**Comment by joe9663** [comment]
reported in [WP.org forums](https://wordpress.org/support/topic/last-update-mess-all-and-block-no-longer-work/) as well
