### ISSUE TITLE
BG Connect Search - Purchased images do not replace as expected in WP 6.1

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#476]
I used the BG Connect Search to find an image that costs coins. I added it to my page. I purchased the image. When I returned to the page, I had a missing image. (did it twice in a row)

![purchased-image-disappears2](https://user-images.githubusercontent.com/20601160/195363069-c2d92e7c-c546-4e23-b9bb-07ddb24a7cdf.gif)

**Comment by jamesros161** [comment]
After further investigation, this will need to happen in PPB, since no specific hooks / actions are triggered by the image cropping in the editor for Inspirations to attach to.
