### ISSUE TITLE
Autoplay and Loop YouTube Videos in PPB not functioning Properly

### ISSUE THREAD

**Issue by SitesByYogi** [BoldGrid/post-and-page-builder#516]
**Describe the bug**
Following the steps [in this guide](https://www.boldgrid.com/support/page-builder/autoplay-and-loop-youtube-videos-in-wordpress/), Autoplay markup removes itself from HTML in PPB text editor. 
**To Reproduce**
1.  Open YouTube and find your video
2.  Click the Share button below the video
3.  Copy the code from the next screen using the button at the bottom of the panel and add to WordPress
4.  Update Iframe Embed code url with `src="?autoplay=1&playlist=xp_s4zekfz4&loop=1"` and `allow="autoplay;"`
5. Publish Video
6. Verify HTML is still present and check for auto play on live page

I successfully replicated this issue on behalf of a user. It seems the `allow="autoplay;"` removes itself from the iframe. Would be nice if we actually had a control that would allow you to set autoplay in the visual editor.

**Comment by jamesros161** [comment]
Looks like the only issue is that the query variable `mute=1` needs to be added to the string. The `allow="autoplay"` isn't necessary, and doesn't fix the problem either. This was a known issue with Firefox when the article was written, however this has been added to Chrome as well. see https://developer.chrome.com/blog/autoplay/
