### ISSUE TITLE
Image Cropping hangs

### ISSUE THREAD

**Issue by rramo012** [BoldGrid/post-and-page-builder#55]
I was replacing an image on the page with a different sized image. The crop image screen comes up but closes very quickly. The image is replaced but not sized correctly so the design is thrown off. Console errors from Chrome are attached - top one in the gif appeared when I initially opened the Editor and the second one was when I was replacing the image.

Let me know if you want the console errors from Firefox too.

**Comment by rramo012** [comment]
Testing Instructions

- Insert an image to a post
- Click on the image 
- Use the toolbar over the image to "Replace"
- Select a new image and insert
- [Expected] Cropping image feature should display
- Crop & Replace Image
- [Expected] Inserted image should cropped and replaced

**Comment by bwmarkle** [comment]
Tested.
