### ISSUE TITLE
New page elements getting added to the top of page content

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/post-and-page-builder#60]
**Describe the bug**
Adding a new page element using the available tools always seems to place the new item at the top of the page content area instead of where the cursor is positioned.

**Expected behavior**
New elements should be added at the cursor position if possible.

**Comment by bwmarkle** [comment]
What version of WordPress?

What version of the P&PB?

Which browser?

**Comment by boldgrid-support** [comment]
**WordPress Version**: 4.9.9
**PPB Version**: 1.6.5
**Browser**: Firefox & Chrome

**Comment by bwmarkle** [comment]
The P&PB version 1.6.5 is a bit outdated. Can you try with [the latest version](https://wordpress.org/plugins/post-and-page-builder/), 1.9.2

**Comment by bwmarkle** [comment]
Any update on this issue? Can it be closed?

**Comment by boldgrid-support** [comment]
Just tested with version 1.10, bug appears to be fixed.
