### ISSUE TITLE
Add a "click here to download P&PB Premium" link.

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/post-and-page-builder#65]
See screenshot: 
![image](https://user-images.githubusercontent.com/5925563/52073398-6648b680-2555-11e9-8cd1-d76fa9de8e2c.png)

Similar to how the BoldGrid Backup plugin does it here - https://github.com/BoldGrid/boldgrid-backup/blob/e8fd713ef51aaf1985d68b89a385be6545dfe68e/admin/class-boldgrid-backup-admin-go-pro.php#L116

**Comment by rramo012** [comment]
Fixed with: https://github.com/BoldGrid/post-and-page-builder/commit/343690f3fa0aa6937d5a291ebf5be48cc16cb8ca
