### ISSUE TITLE
Bug: Parallax image background tiles in mobile display

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/post-and-page-builder#74]
**Describe the bug**
When using the parallax setting for a background image, the image tiles instead of filling the available space.

**To Reproduce**
1. Edit a page and set a parallax image background on a section.
2. View the page in a mobile screen size.
3. See multiple instances of the background image.

**Expected behavior**
Only a single image should display across the available background space.

**Screenshots**
![image](https://user-images.githubusercontent.com/45979457/56055616-e777b300-5d27-11e9-800c-4ebbbaa0766c.png)

![image](https://user-images.githubusercontent.com/45979457/56055627-ed6d9400-5d27-11e9-864e-a24e4e5146d1.png)

**Desktop**
 - OS: Fedora 28
 - Browser: Firefox 66.0.2 and Chromium 73.0.3683.86

**Comment by timelsass** [comment]
Requested to be moved to post and page builder repo by reporter
