### ISSUE TITLE
Bug: Used Blocks and Block Library with Event Calendar WD activated

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/post-and-page-builder#83]
**Describe the bug**
While the Event Calendar WD plugin is activated the Used Block and Block Library options do not load in the Add Block interface.

**To Reproduce**
1. Install [Event Calendar WD](https://wordpress.org/plugins/event-calendar-wd/)
2. Click Add Block while editing a page
3. Select Used Blocks or Block Library from the appropriate dropdowns.

**Expected behavior**
Used Blocks and Block Library should load like the other selections.

**Screenshots**
![image](https://user-images.githubusercontent.com/45979457/58202669-234a5480-7ca6-11e9-951f-90815a3b54f6.png)

**Comment by rramo012** [comment]
I was unable to replicate with version Version 1.1.32 of Event Calendar & 1.11.2 of the post & page builder. Are you still able to replicate? If so what versions of the plugins are you using.

**Comment by joe9663** [comment]
Everything is working as expected on my end too, looks like this isn't a problem any more.

**Comment by rramo012** [comment]
Thanks
