### ISSUE TITLE
Add control to remove background from Blocks

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/post-and-page-builder#93]
**Is your feature request related to a problem? Please describe.**
After adding a block that includes a stock photo background, there is no straightforward way to remove the background image, only replace it with a color or pattern. This leads to a confusing user experience, requiring the user to select their background color from the palette.

**Describe the solution you'd like**
Add a control to "remove" the background to the Background dialogue modal:
![Selection_736](https://user-images.githubusercontent.com/8019842/60834543-2332e500-a17e-11e9-90f2-2e6652086400.png)

**Describe alternatives you've considered**
The alternative solutions that I have considered are using a transparent color for the background, or choosing the background color from the palette options, neither of which provide a clear journey to a user who simply wishes to "remove" the stock photo.

**Additional context**
Feedback from user question on Facebook:
https://www.facebook.com/groups/BGTeamOrange/permalink/667285903739437/

**Comment by rramo012** [comment]
![image](https://user-images.githubusercontent.com/5629738/68349365-f14d7300-00ca-11ea-88f1-e8b05ac89e25.png)

**Comment by rramo012** [comment]
Releases within a week. Version: 1.12.0
