### ISSUE TITLE
No longer available in 1.10.4

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/post-and-page-builder#95]
> WHAT HAVE YOU DONE!!!!!
> 
> Boldgrid Visual Editor is no longer available in Word Press with Post and Page Builder by BoldGrid 1.10.04 updated 2 hours ago
> 
> AAARRRRHHHH!!!!!!

_Originally posted by @gidders28 in https://github.com/BoldGrid/boldgrid-backup/pull/98#issuecomment-510148790_

**Comment by bwmarkle** [comment]
Hi @gidders28,

Hopefully we can get can a quick solution for you on this problem. Can you give us a bit more information on the problem you're having?

When you reference the **BoldGrid Visual Editor**, you're referring to the editor highlighted in red below, correct?
![image](https://user-images.githubusercontent.com/5925563/60990192-df72e380-a315-11e9-8f5c-a6543c82eb12.png)

What do you mean exactly when you say it's **no longer available**? Is it there and just not working right, or do you see a different editor? Such as one of the editors below?

Classic Editor
![image](https://user-images.githubusercontent.com/5925563/60990314-2365e880-a316-11e9-80d0-04e7a3e37a2f.png)

WordPress Editor
![image](https://user-images.githubusercontent.com/5925563/60990350-37114f00-a316-11e9-88a7-0a778851fc16.png)

**Comment by gidders28** [comment]
I just see the WordPress editor

**Comment by bwmarkle** [comment]
Thanks for getting back to us so quickly @gidders28!

Can you try the following please and let us know if it helps:
![image](https://user-images.githubusercontent.com/5925563/60990797-35945680-a317-11e9-8ee7-3ed19234775e.png)

**Comment by gidders28** [comment]
When I click the 3 dot menu I don't get a boldgrid option

See attached
[Doc1.docx](https://github.com/BoldGrid/post-and-page-builder/files/3378753/Doc1.docx)

Got to go out now

**Comment by bwmarkle** [comment]
Hi @gidders28, One of the neat features of GitHub here is you can actually copy and paste images directly into your response. For reference, here's the image you uploaded:
![image](https://user-images.githubusercontent.com/5925563/60991246-2bbf2300-a318-11e9-8160-ad8f08c40dd7.png)

**2 Questions:**
* When you updated the _Post and Page Builder plugin_ to version 1.10.4, did you update anything else?
* When you go to your Plugins page, is the _Post and Page Builder_ listed as an Active plugin? Or did it somehow get deactivated?

**Comment by gidders28** [comment]
Hi

I didn't update to version 1.10.04 it happened automatically .

I haven't updated anything else unless it has happened automatically

The plugin is listed & active

**Comment by rramo012** [comment]
Sounds like an error might be occurring within your browser. Since I cannot replicate it on my side, can you send me any console errors that may be displayed?

Here's an article that can help you display these errors: https://wordpress.org/support/article/using-your-browser-to-diagnose-javascript-errors/#chrome 

Can you send us any errors that display in your console and the which browser your using?

As an interim solution, another way you can change your default editor is in the settings page: 
![image](https://user-images.githubusercontent.com/5629738/60995188-033b2700-a320-11e9-939d-aca0cedc5fda.png)

**Comment by gidders28** [comment]
Am out now - will have a look later &

**Comment by rramo012** [comment]
Our support staff has reached out and let me know that they addressed this issue for you. Please reopen this issue if you continue to experience problems.

**Comment by gidders28** [comment]
Hi

I'm using Chrome. I think those instructions for displaying errors are out
of date.

Going via Menu> More Tools > Developer Tools brings up a window but
pressing CTRL + Shift + J just closes the window.

In the window is a panel labeled Console with this messages - I don't know
if that's what you want?

JQMIGRATE: Migrate is installed, version 1.4.1
300-250.jpg:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2ai_editor_button.js:1 Failed to load resource: the server responded with a
status of 404 (Not Found)
?v=2.0:6 WebSocket connection to 'wss://
public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error
during WebSocket handshake: Unexpected response code: 403
g @ ?v=2.0:6
_ @ ?v=2.0:6
o @ ?v=2.0:6
post.php?post=467&action=edit:1 Unchecked runtime.lastError: The message
port closed before a response was received.
?v=2.0:6 WebSocket connection to 'wss://
public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error
during WebSocket handshake: Unexpected response code: 403
g @ ?v=2.0:6
?v=2.0:6 WebSocket connection to 'wss://
public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error
during WebSocket handshake: Unexpected response code: 403
g @ ?v=2.0:6
_ @ ?v=2.0:6
o @ ?v=2.0:6

_________________

Clearing my Bluehost & wordpress cookies seams to have corrected the
problem for the time being

Regards

**Comment by rramo012** [comment]
Yes that's it. Are you still experiencing an issue with the builder?

**Comment by gidders28** [comment]
I've had a message from someone else at boldgrid responding to my bug
report to say the the post & page builder had not installed properly on my
wordpress site but they've corrected it

It now seems to be working

**Comment by rramo012** [comment]
Good to hear. Let us know if you run into any further issues
