### ISSUE TITLE
Feature: Add controls for HTML tables

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/post-and-page-builder#98]
**Is your feature request related to a problem? Please describe.**
Currently there does not appear to be a way to create or edit table elements through the interface.

**Describe the solution you'd like**
Add Tables to list of available Block Components along with controls to add/remove rows and columns to existing table elements.

**Describe alternatives you've considered**
Creating/editing tables has to be done using the Text editor or switching to WordPress/Gutenberg to add and manage the element.

**Comment by joe9663** [comment]
+1 for this feature from UserEcho

**Comment by nicolepaschen** [comment]
tables have been added!
